[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/old-page"
to = "/new-page"
status = 301

[[redirects]]
from = "/api/externa/*"
to = "https://api-externa.com/:splat"
status = 200
force = true

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY" # Evita que tu web se muestre en iframes (protección clickjacking)
X-Content-Type-Options = "nosniff" # Evita que navegadores interpreten archivos como otros tipos (protección MIME)
Referrer-Policy = "strict-origin-when-cross-origin" # Controla qué información se envía en el referer
Permissions-Policy = "geolocation=(), microphone=(), camera=()" # Desactiva APIs de navegador que no usas
Strict-Transport-Security = "max-age=31536000; includeSubDomains" # Fuerza HTTPS