-- Ejecutar una vez en Supabase antes de usar las cuentas vinculadas.
create table if not exists public.cuentas_vinculadas (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    proveedor text not null,
    proveedor_user_id text not null,
    username text,
    profile_url text,
    avatar_url text,
    metadata jsonb not null default '{}'::jsonb,
    verified_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    unique (proveedor, proveedor_user_id),
    unique (user_id, proveedor)
);

alter table public.cuentas_vinculadas enable row level security;

create policy "Las cuentas vinculadas son públicas"
    on public.cuentas_vinculadas for select
    using (true);

create policy "Cada usuario gestiona sus cuentas vinculadas"
    on public.cuentas_vinculadas for all
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);